name: Track
on:
  schedule:
    - cron: '12 */3 * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  track:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup jq
        run: sudo apt-get -y update && sudo apt-get -y install jq
      - name: Run track.sh
        run: ./track.sh
